(ns agenta.core
  (:import (agenta Engine PanelViewer PanelViewerFrame SingleRandom UnitTypeBuilder)))

(def default-units
  "This piece of data is a good candidate for extraction into edn file"
  [(-> (UnitTypeBuilder.)
       (.setName "Footman")
       (.setBaseAttack 5)
       (.setRandAttack 6)
       (.setRange 1.45)
       (.setAttackSpeed 25)
       (.setVisibility 7)
       (.setSpeed 40)
       (.setHitPoints 70)
       (.build))
   (-> (UnitTypeBuilder.)
       (.setName "Archer")
       (.setBaseAttack 3)
       (.setRandAttack 5)
       (.setRange 5.5)
       (.setAttackSpeed 40)
       (.setVisibility 7)
       (.setSpeed 40)
       (.setHitPoints 55)
       (.build))
   (-> (UnitTypeBuilder.)
       (.setName "Knight")
       (.setBaseAttack 9)
       (.setRandAttack 7)
       (.setRange 1.45)
       (.setAttackSpeed 40)
       (.setVisibility 7)
       (.setSpeed 25)
       (.setHitPoints 110)
       (.build))])

(defn -main [& args]
  (let [p (new PanelViewer)
        u (clojure.edn/read-string (slurp "placement.edn"))
        e (new Engine (SingleRandom/get) (:player0 u) (:player1 u))
        f (new PanelViewerFrame "Agenta example" p)]
    (.init e default-units)
    (.addViewer e p)
    (while (== (.getWinner e) -1)
        (.step e))
    (.showEndMessage f (String/format "Player %d has won after %d ticks!"
                                      (object-array [(.getWinner e)
                                                     (.getTicks e)])))))
